name: jampa_flutter
description: "Jampa, in Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State management
  flutter_bloc: ^9.1.1
  # Navigation
  go_router: ^16.3.0

  # Data management
  get_it: ^8.2.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  shared_preferences: ^2.5.3
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  http: ^1.5.0
  equatable: ^2.0.7
  collection: ^1.19.1

  # Obfuscation
  envied: ^1.3.1
  # Internationalization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  #Forms
  formz: ^0.8.0
  multi_dropdown: ^3.0.1

  # File management
  path_provider: ^2.1.5

  # Alarm management
  permission_handler: ^12.0.1
  workmanager: ^0.9.0+3
  alarm: ^5.1.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  drift_dev: ^2.29.0
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
